name: xchat
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  http_cache_hive_store: ^5.0.1
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^16.0.0
  http_parser: ^4.1.2
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.6.0
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.0.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^3.0.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/src/constants/gen/
  integrations:
    flutter_svg: true
